version: "3.1"
services:
    redis:
        image: redis:alpine
        container_name: trend-consulting-redis

    mysql:
        image: mysql:8.0
        working_dir: /application
        container_name: trend-consulting-mysql
        volumes:
            - .:/application
            - trend-consulting-mysql-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "trend-consulting"
            MYSQL_USER: "username"
            MYSQL_PASSWORD: "password"
        ports:
            - "7012:3306"

    webserver:
        image: nginx:alpine
        working_dir: /application
        container_name: trend-consulting-nginx
        depends_on:
            - php-fpm
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"

    php-fpm:
        build: phpdocker/php-fpm
        container_name: trend-consulting-php-fpm
        depends_on:
            - mysql
            - redis
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/99-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini

    node:
        image: node:18
        container_name: trend-consulting-node
        working_dir: /application
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/application
        command: "tail -f /dev/null"
        ports:
            - "5173:5173"
        depends_on:
            - php-fpm

volumes:
    trend-consulting-mysql-volume:
